[audio]
enable_overdrive = false
enable_sounds = false
notification_sound = ""
sound_volume = 0.5
volume_change_sound = ""

[backdrop]
blur_intensity = 0.5
enabled = false
tint_intensity = 0.30000001192092896

[bar]
order = [ "main" ]

    [bar.main]
    auto_hide = false
    background_opacity = 0.75
    border = "outline"
    border_width = 0.0
    capsule = true
    capsule_fill = "surface_variant"
    capsule_group = []
    capsule_opacity = 1.0
    capsule_padding = 6.0
    capsule_thickness = 0.75999999046325684
    center = [ "date", "control-center", "clock" ]
    contact_shadow = false
    enabled = true
    end = [
        "media",
        "weather",
        "tray",
        "clipboard",
        "notifications",
        "bluetooth",
        "network",
        "volume",
        "battery",
        "launcher"
    ]
    font_weight = 500
    layer = "top"
    margin_edge = 10
    margin_ends = 10
    margin_opposite_edge = 0
    padding = 10
    panel_overlap = 2
    position = "top"
    radius = 12
    radius_bottom_left = 6
    radius_bottom_right = 6
    radius_top_left = 6
    radius_top_right = 6
    reserve_space = true
    scale = 1.0
    shadow = true
    start = [ "workspaces" ]
    thickness = 30
    widget_spacing = 4

        [bar.main.dead_zone]
        command = ""
        middle_command = ""
        right_command = ""
        scroll_down_command = ""
        scroll_up_command = ""

        [bar.main.monitor.DP-2]
        auto_hide = false
        background_opacity = 0.75
        border = "outline"
        border_width = 0.0
        capsule = true
        capsule_fill = "surface_variant"
        capsule_opacity = 1.0
        capsule_padding = 6.0
        capsule_thickness = 0.75999999046325684
        center = [ "date", "clock" ]
        contact_shadow = false
        enabled = true
        end = [ "group:g1" ]
        font_weight = 500
        layer = "top"
        margin_edge = 10
        margin_ends = 10
        margin_opposite_edge = 0
        match = "DP-2"
        padding = 10
        panel_overlap = 2
        position = "bottom"
        radius = 12
        radius_bottom_left = 6
        radius_bottom_right = 6
        radius_top_left = 6
        radius_top_right = 6
        reserve_space = true
        scale = 1.0
        shadow = true
        start = [ "workspaces" ]
        thickness = 30
        widget_spacing = 4

            [bar.main.monitor.DP-2.dead_zone]
            command = ""
            middle_command = ""
            right_command = ""
            scroll_down_command = ""
            scroll_up_command = ""

            [[bar.main.monitor.DP-2.capsule_group]]
            fill = "surface_variant"
            id = "g1"
            members = [ "network_rx", "ram", "temp" ]
            opacity = 1.0
            padding = 6.0

[battery]
warning_threshold = 20

[brightness]
enable_ddcutil = true
ignore_mmids = []
minimum_brightness = 0.0

[calendar]
enabled = true
refresh_minutes = 15

    [calendar.account.personal_google]
    calendars = []
    color = ""
    name = "Gmail Main"
    provider = ""
    server_url = ""
    type = "google"
    username = ""

    [calendar.account.school_google]
    calendars = []
    color = ""
    name = "University of Belize"
    provider = ""
    server_url = ""
    type = "google"
    username = ""

[control_center]
sidebar = "full"
sidebar_section = "full"
width = 800

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "dark_mode"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "nightlight"

[desktop_widgets]
enabled = false
schema_version = 1

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

[dock]
active_monitor_only = true
active_opacity = 1.0
active_scale = 1.0
auto_hide = true
background_opacity = 0.75
cross_axis_padding = 8
enabled = true
icon_size = 30
inactive_opacity = 1.0
inactive_scale = 1.0
item_spacing = 4
launcher_icon = "grid-dots"
launcher_position = "start"
magnification = true
magnification_scale = 1.4500000476837158
main_axis_padding = 16
margin_edge = 8
margin_ends = 0
monitors = []
pinned = []
position = "bottom"
radius = 8
radius_bottom_left = 16
radius_bottom_right = 16
radius_top_left = 16
radius_top_right = 16
reserve_space = false
shadow = true
show_dots = false
show_instance_count = true
show_running = true

[hooks]
battery_charging = []
battery_discharging = []
battery_percentage_changed = []
battery_plugged = []
bluetooth_disabled = []
bluetooth_enabled = []
colors_changed = []
logging_out = []
power_profile_changed = []
rebooting = []
session_locked = []
session_unlocked = []
shutting_down = []
started = []
theme_mode_changed = []
wallpaper_changed = []
wifi_disabled = []
wifi_enabled = []

[idle]
behavior_order = [ "lock", "screen-off" ]
pre_action_fade_seconds = 2.0

    [idle.behavior.lock]
    action = "lock"
    command = "noctalia:screen-lock"
    enabled = false
    resume_command = ""
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    command = "noctalia:dpms-off"
    enabled = false
    resume_command = "noctalia:dpms-on"
    timeout = 660

[keybinds]
cancel = [ "Escape" ]
down = [ "Down" ]
left = [ "Left" ]
right = [ "Right" ]
up = [ "Up" ]
validate = [ "Return", "KP_Enter" ]

[location]
address = "Belmopan, Belize"
auto_locate = false
sunrise = ""
sunset = ""

[lockscreen]
allow_empty_password = false
blur_intensity = 0.5
blurred_desktop = false
enabled = true
fingerprint = true
monitors = []
tint_intensity = 0.30000001192092896
wallpaper = ""

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@DP-2",
    "lockscreen-login-box@DP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1024.0
    cy = 1049.0
    enabled = true
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 70.0
    box_width = 400.0
    cx = 576.0
    cy = 1933.0
    enabled = true
    output = "DP-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        show_login_button = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 128.0
    box_width = 288.0
    cx = 208.0
    cy = 256.0
    enabled = true
    output = "DP-1"
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background_opacity = 0.80000000000000004
        forecast_days = 3
        shadow = false
        show_forecast = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 96.0
    box_width = 288.0
    cx = 208.45285034179688
    cy = 112.0
    enabled = true
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        clock_style = "digital"
        format = "{:%-I:%M %p}"

[nightlight]
enabled = false
force = false
temperature_day = 6500
temperature_night = 4900

[notification]
background_opacity = 0.75
collapse_on_dismiss = true
enable_daemon = true
layer = "top"
monitors = [ "DP-1" ]
offset_x = 10
offset_y = 10
position = "top_right"
scale = 1.0
show_actions = true
show_app_name = true

[osd]
background_opacity = 0.75
monitors = [ "DP-1" ]
offset_x = 10
offset_y = 10
orientation = "horizontal"
position = "top_right"
position_vertical = "top_center"
scale = 1.0

    [osd.kinds]
    bluetooth = true
    brightness = true
    caffeine = true
    dnd = true
    keyboard_layout = true
    lock_keys = true
    media = true
    nightlight = true
    power_profile = true
    privacy = true
    volume = true
    volume_input = true
    volume_output = true
    wifi = true

[plugins]
enabled = []

    [[plugins.source]]
    auto_update = true
    enabled = true
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    auto_update = true
    enabled = true
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
app_icon_colorize = false
avatar_path = "~/Pictures/nixconfig-avatars/crow.png"
clipboard_auto_paste = "auto"
clipboard_confirm_clear_history = false
clipboard_enabled = true
clipboard_history_max_entries = 25
clipboard_image_action_command = ""
corner_radius_scale = 0.5
date_format = "%A, %x"
disable_mipmaps = false
font_family = "Noto Sans"
lang = "en"
launch_apps_as_systemd_services = false
middle_click_opens_widget_settings = true
niri_overview_type_to_launch_enabled = true
offline_mode = false
password_style = "random"
polkit_agent = true
screen_time_enabled = true
settings_show_advanced = true
setup_wizard_enabled = true
shared_gl_context = true
show_location = true
telemetry_enabled = true
time_format = "{:%-I:%M %p}"
ui_scale = 1.0

    [shell.animation]
    enabled = true
    speed = 1.0

    [shell.mpris]
    blacklist = []

    [shell.panel]
    borders = false
    clipboard_placement = "attached"
    control_center_placement = "attached"
    floating_offset = 8
    launcher_app_grid = false
    launcher_categories = false
    launcher_compact = false
    launcher_placement = "centered"
    launcher_session_search = true
    launcher_show_icons = true
    launcher_sort_by_usage = true
    open_near_click_clipboard = true
    open_near_click_control_center = false
    open_near_click_launcher = false
    open_near_click_session = false
    open_near_click_wallpaper = false
    session_placement = "attached"
    shadow = true
    transparency_mode = "glass"
    wallpaper_placement = "attached"

    [shell.privacy]
    cam_filter_regex = ""
    mic_filter_regex = ""

    [shell.screen_corners]
    enabled = false
    size = 32

    [shell.screenshot]
    confirm_region = true
    copy_to_clipboard = true
    directory = ""
    filename_pattern = ""
    freeze_screen = true
    pipe_command = ""
    pipe_to_command = false
    save_to_file = true

    [shell.session.power]

    [[shell.session.actions]]
    action = "lock"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    command = ""
    enabled = true
    glyph = ""
    label = ""
    shortcut = "5"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.5
    direction = "down_left"

[system.monitor]
cpu_poll_seconds = 2.0
cpu_temp_activity_threshold = 60.0
cpu_temp_critical_threshold = 85.0
cpu_temp_sensor_path = ""
cpu_usage_activity_threshold = 10.0
cpu_usage_critical_threshold = 100.0
disk_pct_activity_threshold = 80.0
disk_pct_critical_threshold = 99.0
disk_poll_seconds = 10.0
enabled = true
gpu_poll_seconds = 5.0
gpu_temp_activity_threshold = 60.0
gpu_temp_critical_threshold = 85.0
gpu_usage_activity_threshold = 40.0
gpu_usage_critical_threshold = 70.0
gpu_vram_activity_threshold = 20.0
gpu_vram_critical_threshold = 80.0
memory_poll_seconds = 2.0
net_rx_activity_threshold = 0.20000000000000001
net_rx_critical_threshold = 10.0
net_tx_activity_threshold = 0.20000000000000001
net_tx_critical_threshold = 10.0
network_poll_seconds = 3.0
ram_pct_activity_threshold = 30.0
ram_pct_critical_threshold = 90.0
swap_pct_activity_threshold = 70.0
swap_pct_critical_threshold = 90.0

[theme]
builtin = "Noctalia"
community_palette = "Osaka jade"
custom_palette = ""
mode = "auto"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kcolorscheme", "qt" ]
    community_ids = []
    enable_builtin_templates = true
    enable_community_templates = true

[wallpaper]
directory = "~/Pictures/Wallpapers"
directory_dark = ""
directory_light = ""
edge_smoothness = 0.30000001192092896
enabled = true
fill_color = ""
fill_mode = "crop"
per_monitor_directories = false
transition = [ "honeycomb" ]
transition_duration = 1500.0
transition_on_startup = true

    [wallpaper.automation]
    enabled = false
    interval_seconds = 1800
    order = "random"
    recursive = true

    [wallpaper.default]
    path = "~/Pictures/Wallpapers/nixconfig-wallpapers/tnt-camp.jpg"

[weather]
effects = true
enabled = true
refresh_minutes = 30
unit = "imperial"

[widget.active_window]
icon_size = 14.0
max_length = 260.0
min_length = 80.0
title_scroll = "none"
type = "active_window"

[widget.audio_visualizer]
anchor = true
type = "audio_visualizer"

[widget.bongocat]
audio_spectrum = true
script = "scripts/bongocat.lua"
tappy_mode = true
type = "scripted"

[widget.brightness]
show_label = false
type = "brightness"

[widget.clock]
format = "{:%-I:%M %p}"
type = "clock"

[widget.control-center]
anchor = true
glyph = "paw-filled"
type = "control-center"

[widget.cpu]
stat = "cpu_usage"
type = "sysmon"

[widget.date]
format = "{:%A %e %b %Y}"
type = "clock"

[widget.input_volume]
device = "input"
type = "volume"

[widget.keyboard_layout]
cycle_command = ""
hide_when_single_layout = false
type = "keyboard_layout"

[widget.lock_keys]
display = "short"
hide_when_off = false
show_caps_lock = true
show_num_lock = true
show_scroll_lock = false
type = "lock_keys"

[widget.media]
art_size = 16.0
hide_when_no_media = true
max_length = 220.0
min_length = 80.0
title_scroll = "always"
type = "media"

[widget.network]
show_label = false
type = "network"

[widget.network_rx]
stat = "net_rx"
type = "sysmon"

[widget.network_tx]
stat = "net_tx"
type = "sysmon"

[widget.output_volume]
device = "output"
type = "volume"

[widget.privacy]
anchor = true
type = "privacy"

[widget.ram]
stat = "ram_used"
type = "sysmon"

[widget.spacer]
type = "spacer"

[widget.sysmon]
stat = "cpu_temp"
type = "sysmon"

[widget.temp]
stat = "cpu_temp"
type = "sysmon"

[widget.tray]
drawer = true
drawer_columns = 5
match_adjacent_spacing = true
type = "tray"

[widget.volume]
show_label = false
type = "volume"

[widget.weather]
show_condition = false
type = "weather"

[widget.workspaces]
display = "name"
max_label_chars = 10
type = "workspaces"
