# adapted from https://github.com/antholeole/nixconfig

add_newline = false

format = "$character"
right_format = "[ $directory $git_branch](bg:#38528a fg:#fdb00b)"

[character]
success_symbol = "[󰘧](fg:#4d6fb7)"
error_symbol = "[󰘧](fg:#fdb00b)"
format = "$symbol "

[directory]
format = "$path"
truncation_length = 1

[git_branch]
format = "\\[$branch\\] "
